#!/usr/bin/env bash
node_exp_version='1.2.2'
username='node_exporter'

if [ -z $(which gunzip) ]; then sudo apt install -y gunzip; fi
wget "https://github.com/prometheus/node_exporter/releases/download/v${node_exp_version}/node_exporter-${node_exp_version}.linux-amd64.tar.gz"
tar xf node_exporter-${node_exp_version}.linux-amd64.tar.gz && mv node_exporter-${node_exp_version}.linux-amd64/node_exporter /usr/sbin/
rm -rf node_exporter-${node_exp_version}.linux-amd64*
adduser --system --no-create-home --group ${username}
systemctl enable node_exporter.service --now

